language: node_js
node_js: stable
branches:
  only:
  - hexo
cache:
  directories:
    - node_modules
before_install:
  - git config --global user.name "xhusky"
  - git config --global user.email "wsg115@126.com"
  - npm install -g hexo-cli
install:
  - npm install
  - npm install ejs
script:
  - hexo clean
  - hexo generate
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
 global:
    - GH_REF: github.com/xhusky/xhusky.github.io.git

